version: '3.7'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    env_file:
      - .env
    volumes:
    - ./api/:/usr/src/api/
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - spd:/var/lib/postgresql/data/
    env_file:
      - db.env

volumes:
  spd: